services:
  openhab_demo:
    image: openhab/openhab:5.0.1-debian
    container_name: openhab_demo
    hostname: ohdemo
    restart: always
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      CRYPTO_POLICY: "unlimited"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./openhab_demo/conf:/openhab/conf
      - ./openhab_demo/userdata:/openhab/userdata
      - ./openhab_demo/addons:/openhab/addons
    ports:
      - 127.0.0.1:8080:8080

  openhab_private:
    image: openhab/openhab:5.0.1-debian
    container_name: openhab_private
    hostname: ohmock
    restart: always
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      CRYPTO_POLICY: "unlimited"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./openhab_private/conf:/openhab/conf
      - ./openhab_private/userdata:/openhab/userdata
      - ./openhab_private/addons:/openhab/addons
    ports:
      - 127.0.0.1:18080:8080

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/conf:/etc/influxdb2
    ports:
      - 127.0.0.1:8086:8086

secrets:
  influxdb2-admin-username:
    file: ~/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ~/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ~/.env.influxdb2-admin-token
